steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$(cat package.json | jq -r .version)'  # 使用 package.json 的版本号
    - '--build-arg'
    - 'ENV_NAME=prod'
    - '.'

# 使用 CLOUD_LOGGING_ONLY 进行日志记录
options:
  logging: CLOUD_LOGGING_ONLY

# 推送镜像到 GCR
images:
- 'asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$(cat package.json | jq -r .version)'  # 确保推送的镜像名称与构建时的名称一致
