steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$BUILD_ID'  # 使用内建的 $BUILD_ID 作为版本号
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$BUILD_ID'  # 推送镜像


# 使用 CLOUD_LOGGING_ONLY 进行日志记录
options:
  logging: CLOUD_LOGGING_ONLY
