steps:
- name: 'node:14-alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      VERSION=$(node -p "require('./package.json').version") && \
      echo "Version is $VERSION" && \
      echo $VERSION > /workspace/version.txt  # 将版本号保存到文件

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$(cat /workspace/version.txt)'  # 从文件中读取版本号
    - '.'

- options:
  logging: CLOUD_LOGGING_ONLY  # 确保 options 部分正确缩进

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$(cat /workspace/version.txt)'  # 从文件中读取版本号并推送
