steps:
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      VERSION=$(jq -r .version package.json) && \
      echo "Building image with version: $VERSION" && \
      docker build -t asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$VERSION . 

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$(jq -r .version package.json)'  # 推送镜像

# 使用 CLOUD_LOGGING_ONLY 进行日志记录
options:
  logging: CLOUD_LOGGING_ONLY

# 推送镜像到 GCR
images:
- 'asia-east1-docker.pkg.dev/$PROJECT_ID/dockers/tender_vue:$(jq -r .version package.json)'  # 确保推送的镜像名称与构建时的名称一致
